version: "3"
services:
  dsemu:
    image: google/cloud-sdk:244.0.0
    ports:
      - "8081:8081"
    command: gcloud --project=oauth2idp beta emulators datastore start --host-port=0.0.0.0:8081 --no-store-on-disk --consistency=1.0
